controller_list:
  - name: fake_Left_Arm_controller
    joints:
      - lshoulder_joint
      - l2shoulder_joint
      - lupperarm_joint
      - lelbow_joint
      - lforearm_joint
      - lwrist_joint
  - name: fake_Right_Arm_controller
    joints:
      - rshoulder_joint
      - r2shoulder_joint
      - rupperarm_joint
      - relbow_joint
      - rforearm_joint
      - rwrist_joint
  - name: fake_Left_Hand_controller
    joints:
      - lwrist_joint
  - name: fake_Right_Hand_controller
    joints:
      - rwrist_joint
  - name: fake_Head_controller
    joints:
      []